### ISSUE TITLE
unexpected keyword argument 'language' at initialization/setup of integration.

### ISSUE THREAD

**Issue by vinceke44** [Hyundai-Kia-Connect/kia_uvo#565]
region/car: EU/ Kia EV6

component version: 2.5.3
Home Assistant version: 2023.1.2

After upgrading the component to 2.5.3 it stopped working. The integration can no longer enable properly and generates an error.

Only entry in the HA logs (with logger set to debug) is:

2023-01-11 15:46:26.650 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Kia Europe <email@address> for kia_uvo
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 382, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/kia_uvo/__init__.py", line 51, in async_setup_entry
    coordinator = HyundaiKiaConnectDataUpdateCoordinator(hass, config_entry)
  File "/config/custom_components/kia_uvo/coordinator.py", line 55, in __init__
    self.vehicle_manager = VehicleManager(
TypeError: VehicleManager.__init__() got an unexpected keyword argument 'language'

Rolling back to version 2.10 everything starts working as expected again. All versions after that exhibit the behavior and error as described above. I've tried the usual steps like deleting and recreating the integration, and doing a complete un- and reinstallation of the component. The result is the same.

**Comment by cdnninja** [comment]
What language is your home assistant set to and what version of home assistant are you using?

**Comment by vinceke44** [comment]
2023.1.2  Language is set to English.

**Comment by cdnninja** [comment]
I am running same version and language and can't replicate this.  What is home assistant running on top of from an OS standpoint? 

Any errors in home assistant core logs related to the API package not updating?   Other thing to check is if you can edit the custom_component directory and check the manifest.json file that it shows the API version as 2.3.2.

**Comment by vinceke44** [comment]
Strange. I'm running Home assistant in a docker container. There's no other errors in my logs and the manifest.json file shows api version 2.3.2. 

As the component works properly in 2.1.0 and stopped working with 2.2.0, I would wager a guess that this new feature is at the heart of the issue:

EU: Support for language (https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/521) (https://github.com/Hyundai-Kia-Connect/kia_uvo/commit/d430e79fbc5d42055f81b725254fe1016c75904f))

**Comment by vinceke44** [comment]
Definitely related to the feature request:

In both config_flow.py and coordinator.py the line:
        language=hass.config.language, 
is causing the problem. I've tried setting the value of language statically to English (and Dutch) but that did not change the error message. However If I remove the line from both files the integration works as expected. 

Judging from the feature requests origin it seems to be created for a Hyundai/Bluelink. As I am using Kia might the issue be found there?

**Comment by cdnninja** [comment]
It is saying the api library doesn't support it.  Since in docker you may have something going on with requirements for install.  Can you manually validate what version of the api is installed within docker?  Pip list may show it in the container if pip is installed.

**Comment by cdnninja** [comment]
As a note we have 100s of people running this version today based on the telemetry data.   So this is something with the docker setup since no one else has reported it.   I am suspecting the api version isn't updating.

**Comment by vinceke44** [comment]
bash-5.1# pip list | grep hyundai
hyundai-kia-connect-api          2.3.2

Looks to be in order. I'm going to spin up a clean home assistant install with just HACS and this plugin. Later today (if my newborn grants me the time that is ;) )

**Comment by vinceke44** [comment]
Clean installation works just fine. I'm a bit puzzled as to what is wrong on my own install though as there's nothing I can think of that differs. Regardless, definitely a me problem.

**Comment by vinceke44** [comment]
found it. As I can't explain how this happened I'll just post it here in case it might help someone:

While my api version was correct according to the pip listing. There was an older version of the api in the <hass config>/deps/lib/python3.10/site-packages folder which was version 1.47.2. Don't know how it got there, also have not seen a version 2.3.2 of the api being dropped here after installing and (successfully) configuring the integration. Regardless all working fine now. 

Sorry for taking up your time cdninja, I appreciate everything your doing. I wish I could do more, but as you could clearly see from my previous remarks, I'm no programmer. ;)

**Comment by cdnninja** [comment]
Glad to hear you figured it out! I'm no pro in this space either. I don't do it for a living just a hobby!
