### ISSUE TITLE
2.45.3 breaks Kia EU login (needs hyundai_kia_connect_api 3.48.1)

### ISSUE THREAD

**Issue by RustyDust** [Hyundai-Kia-Connect/kia_uvo#1348]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU / Kia

**Version of the integration**
2.45.3

**Describe the bug**
Integration throws `AttributeError`

**Debug logs if an error occurred**
```
Oct 16 09:30:10 raspberrypi hass[142180]: Traceback (most recent call last):
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/opt/homeassistant/lib/python3.13/site-packages/homeassistant/helpers/update_coordinator.py", line 392, in _async_refresh
Oct 16 09:30:10 raspberrypi hass[142180]:     self.data = await self._async_update_data()
Oct 16 09:30:10 raspberrypi hass[142180]:                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/coordinator.py", line 109, in _async_update_data
Oct 16 09:30:10 raspberrypi hass[142180]:     await self.async_check_and_refresh_token()
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/coordinator.py", line 171, in async_check_and_refresh_token
Oct 16 09:30:10 raspberrypi hass[142180]:     await self.hass.async_add_executor_job(
Oct 16 09:30:10 raspberrypi hass[142180]:         self.vehicle_manager.check_and_refresh_token
Oct 16 09:30:10 raspberrypi hass[142180]:     )
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/usr/local/lib/python3.13/concurrent/futures/thread.py", line 59, in run
Oct 16 09:30:10 raspberrypi hass[142180]:     result = self.fn(*self.args, **self.kwargs)
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/opt/homeassistant/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 148, in check_and_refresh_token
Oct 16 09:30:10 raspberrypi hass[142180]:     self.initialize()
Oct 16 09:30:10 raspberrypi hass[142180]:     ~~~~~~~~~~~~~~~^^
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/opt/homeassistant/lib/python3.13/site-packages/hyundai_kia_connect_api/VehicleManager.py", line 83, in initialize
Oct 16 09:30:10 raspberrypi hass[142180]:     self.token: Token = self.api.login(self.username, self.password)
Oct 16 09:30:10 raspberrypi hass[142180]:                         ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/opt/homeassistant/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 185, in login
Oct 16 09:30:10 raspberrypi hass[142180]:     _, access_token, authorization_code, expires_in = self._get_access_token(
Oct 16 09:30:10 raspberrypi hass[142180]:                                                       ~~~~~~~~~~~~~~~~~~~~~~^
Oct 16 09:30:10 raspberrypi hass[142180]:         stamp, refresh_token
Oct 16 09:30:10 raspberrypi hass[142180]:         ^^^^^^^^^^^^^^^^^^^^
Oct 16 09:30:10 raspberrypi hass[142180]:     )
Oct 16 09:30:10 raspberrypi hass[142180]:     ^
Oct 16 09:30:10 raspberrypi hass[142180]:   File "/opt/homeassistant/lib/python3.13/site-packages/hyundai_kia_connect_api/KiaUvoApiEU.py", line 1347, in _get_access_token
Oct 16 09:30:10 raspberrypi hass[142180]:     "client_secret": self.CCS_SERVICE_SECRET,
Oct 16 09:30:10 raspberrypi hass[142180]:                      ^^^^^^^^^^^^^^^^^^^^^^^
Oct 16 09:30:10 raspberrypi hass[142180]: AttributeError: 'KiaUvoApiEU' object has no attribute 'CCS_SERVICE_SECRET'
```

**To Reproduce**
Own a Kia and install 2.45.3

**Expected behavior**
As with 2.45.2 ;)

**Screenshots**

**Additional context**

Should be fixed with update to Hyundai_Kia_connect_api 3.48.1 (see https://github.com/Hyundai-Kia-Connect/hyundai_kia_connect_api/commit/dbb9039ef794c67ae7d48cf8518fdae0c2fbdf1d)

**Comment by Gazoonky** [comment]
Has that patch been applied to 2.45.3, or so we need to wait for the next release?

**Comment by posixx** [comment]
Same error after update so it looks like something is missing:

AttributeError: 'KiaUvoApiEU' object has no attribute 'CCS_SERVICE_SECRET'

**Comment by Gazoonky** [comment]
Yes it's that api patch (#922) mentioned in the OP that needs to be added.

**Comment by spfunnell** [comment]
Rolled back to 2.45.2 which is working fine

**Comment by sylvain-prt** [comment]
still have the issue to login even after upgrade to 2.45.4

**Comment by posixx** [comment]
Not for me; working again after update to 2.45.4👍🏻

**Comment by sylvain-prt** [comment]
> Not for me; working again after update to 2.45.4👍🏻

With Kia or Hyundai

I’m owning a Hyundai and using Bluelink and still facing unexpected error message

**Comment by RustyDust** [comment]
> With Kia or Hyundai
> I’m owning a Hyundai and using Bluelink and still facing unexpected error message

Then most likely your problem is different from the one here. Did you change the credentials from using the username/password combo to username/refresh-token? If not, then you may want to try [this script](https://gist.github.com/Maaxion/22a38ba8fb06937da18482ddf35171ac) to generate one and try again.

If you did and you're seeing an error you should open a new issue or look for a related one.

**Comment by sylvain-prt** [comment]
> > With Kia or Hyundai
> > I’m owning a Hyundai and using Bluelink and still facing unexpected error message
> 
> Then most likely your problem is different from the one here. Did you change the credentials from using the username/password combo to username/refresh-token? If not, then you may want to try [this script](https://gist.github.com/Maaxion/22a38ba8fb06937da18482ddf35171ac) to generate one and try again.
> 
> If you did and you're seeing an error you should open a new issue or look for a related one.

Interesting 
What do you mean with username/refresh-token ?

**Comment by RustyDust** [comment]
You may want to read [this](https://github.com/Hyundai-Kia-Connect/kia_uvo/issues/1343#issuecomment-3412635721) - and maybe even the whole issue.
