### ISSUE TITLE
KIA EV3 - Charging and Climate Actions no longer  possible

### ISSUE THREAD

**Issue by SaschaWeiher** [Hyundai-Kia-Connect/kia_uvo#1747]
### Region

EU

### Brand of Car

Kia

### Version of the Integration

3.5.0

### Describe the Bug

Hi,

I've updated to 3.5.0 and now the Charging and Climate Actions are not working. 

HA tells me that the entities are no longer available.

### To Reproduce

Install 3.5.0
Go to Integration
Check availability of Climate and EV Charging Entity Actions

### Expected Behavior

Press the Button and the Action should start.

**Comment by leonvdz** [comment]
Here the same problem. A lot of options are now unavailable. But under the hood of HA I can still reach switch.e_niro_esv_charging.
So I think it's not realy gone, just in the list of the integration....

**Comment by snigehere** [comment]
I see the following entities unavailable (edit to add error message)

entity_id: switch.ioniq6_ioniq6_climate
state: unavailable

entity_id: switch.ioniq6_ioniq6_ev_charging
state: unavailable

entity_id: switch.ioniq6_ev_scheduled_departure_1
state: unavailable

entity_id: switch.ioniq6_ev_scheduled_departure_2
state: unavailable

entity_id: switch.ioniq6_first_departure_climate
state: unavailable

entity_id: switch.ioniq6_first_departure_defrost
state: unavailable

entity_id: switch.ioniq6_scheduled_charging
state: unavailable

entity_id: switch.ioniq6_second_departure_climate
state: unavailable

entity_id: switch.ioniq6_second_departure_defrost
state: unavailable

Log shows
2026-06-27 10:57:16.577 ERROR (MainThread) [homeassistant.components.switch] Error while setting up kia_uvo platform for switch: 'Vehicle' object has no attribute 'valet_mode_active'
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 490, in _async_setup_platform
    await asyncio.shield(awaitable)
  File "/config/custom_components/kia_uvo/switch.py", line 196, in async_setup_entry
    if description.exists_fn(vehicle):
       ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/config/custom_components/kia_uvo/switch.py", line 179, in <lambda>
    exists_fn=lambda vehicle: vehicle.valet_mode_active is not None,
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Vehicle' object has no attribute 'valet_mode_active'

**Comment by rcove** [comment]
I have similar issues, downgrade to 3.4.0 has fixed it for now

**Comment by GasManGeek** [comment]
I can confirm the same issue on a 2025 Kia EV6 (EU) after upgrading to v3.5.0.

The following switch entities became unavailable:

switch.ev6_ev_charging
switch.ev6_climate
switch.ev6_ev_scheduled_departure_1
switch.ev6_ev_scheduled_departure_2
(and the other switch entities)

Sensors continued to work normally and the official Kia app was unaffected.

Home Assistant log:

Error while setting up kia_uvo platform for switch:
'Vehicle' object has no attribute 'valet_mode_active'

(traceback points to switch.py during switch platform setup).

I rolled back to v3.4.0, restarted Home Assistant, and all switch entities (including switch.ev6_ev_charging) were restored and are working again.

Full HA log entry:
Logger: homeassistant.components.switch Source: helpers/entity_platform.py:490 Integration: Switch (documentation, issues) First occurred: 07:20:14 (1 occurrence) Last logged: 07:20:14 Error while setting up kia_uvo platform for switch: 'Vehicle' object has no attribute 'valet_mode_active' Traceback (most recent call last): File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 490, in _async_setup_platform await asyncio.shield(awaitable) File "/config/custom_components/kia_uvo/switch.py", line 196, in async_setup_entry if description.exists_fn(vehicle): ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^ File "/config/custom_components/kia_uvo/switch.py", line 179, in <lambda> exists_fn=lambda vehicle: vehicle.valet_mode_active is not None, ^^^^^^^^^^^^^^^^^^^^^^^^^ AttributeError: 'Vehicle' object has no attribute 'valet_mode_active'

**Comment by snigehere** [comment]
Solved by 3.5.2
