### ISSUE TITLE
1st time Cant login

### ISSUE THREAD

**Issue by madnessi** [Hyundai-Kia-Connect/kia_uvo#524]
Please check Services, Known Bug / Issues and Troubleshooting over here first: https://github.com/fuatakgun/kia_uvo/blob/master/README.md
**Region and Brand of car**
EU, KIA
**Version of the integration**
2.2.0

**Describe the bug**
1st time to add it in to Home Assistant. Failure with login
Unexpected error

**Debug logs if an error occurred**
This error originated from a custom integration.

Logger: custom_components.kia_uvo.config_flow
Source: custom_components/kia_uvo/config_flow.py:58
Integration: Hyundai / Kia Connect (documentation, issues)
First occurred: 12:36:03 PM (2 occurrences)
Last logged: 12:37:35 PM

**To Reproduce**
Yes, every time

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by beanian** [comment]
Try log in using 2.1.0 version from HACS? I cant log in using 2.2 either, had to downgrade to 2.1.0 to get back in

**Comment by cdnninja** [comment]
Latest release solves this.  Sorry about that!

**Comment by thomastitze** [comment]
I'm on 2.2.1 and see the same problem. It is marked as latest release. Is there a newer release?

**Comment by cdnninja** [comment]
If you click redownload and for version pick master it will have my first attempt at a fix.

**Comment by cdnninja** [comment]
You are on the correct version. Could you enable debug logs as outlined in the readme and post your logs?  Removing personal details before posting.

**Comment by thomastitze** [comment]
This is the error message from the log:

2022-12-23 16:30:24.490 ERROR (MainThread) [custom_components.kia_uvo.config_flow] Unexpected exception
Traceback (most recent call last):
File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/config_flow.py", line 159, in async_step_user
await validate_input(self.hass, user_input)
File "/home/homeassistant/.homeassistant/custom_components/kia_uvo/config_flow.py", line 61, in validate_input
language=hass.config.language,
AttributeError: 'Config' object has no attribute 'language'

Looks like some language configuration is missing???

**Comment by fuatakgun** [comment]
What is the home assistant version?

**Comment by thomastitze** [comment]
Home Assistant 2022.11.4
Frontend 20221108.0 - latest

Plan to update to 2022.12.8 today

**Comment by fuatakgun** [comment]
You are probably missing this locale information in old version of home assistant, I would update it and try again afterwards

**Comment by thomastitze** [comment]
Worked after the update to 2022.12.8. Home Assistant required now setting the County and Language option. Thanks!

**Comment by cdnninja** [comment]
Great. I am going to close this out.
